// flow-typed signature: de188df28b1795dc363abdc403b4739b
// flow-typed version: <<STUB>>/comma-number_v^2.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'comma-number'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'comma-number' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'comma-number/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'comma-number/lib/index.js' {
  declare module.exports: $Exports<'comma-number/lib/index'>;
}
