// flow-typed signature: f82c9d1ef4e9fc3288a16edd0d995d3f
// flow-typed version: <<STUB>>/gatsby-plugin-segment_v^1.0.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-segment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-segment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-segment/example/gatsby-config' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-segment/example/src/pages/foo' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-segment/example/src/pages/index' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-segment/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-segment/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-segment/src/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-segment/src/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-segment/example/gatsby-config.js' {
  declare module.exports: $Exports<'gatsby-plugin-segment/example/gatsby-config'>;
}
declare module 'gatsby-plugin-segment/example/src/pages/foo.js' {
  declare module.exports: $Exports<'gatsby-plugin-segment/example/src/pages/foo'>;
}
declare module 'gatsby-plugin-segment/example/src/pages/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-segment/example/src/pages/index'>;
}
declare module 'gatsby-plugin-segment/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-segment/gatsby-browser'>;
}
declare module 'gatsby-plugin-segment/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-segment/gatsby-ssr'>;
}
declare module 'gatsby-plugin-segment/src/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-segment/src/gatsby-browser'>;
}
declare module 'gatsby-plugin-segment/src/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-segment/src/gatsby-ssr'>;
}
