// flow-typed signature: 4b4255226dd4716fb2fcf1171871ed19
// flow-typed version: <<STUB>>/geopattern_v^1.2.3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geopattern'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geopattern' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geopattern/geopattern' {
  declare module.exports: any;
}

declare module 'geopattern/lib/color' {
  declare module.exports: any;
}

declare module 'geopattern/lib/pattern' {
  declare module.exports: any;
}

declare module 'geopattern/lib/sha1' {
  declare module.exports: any;
}

declare module 'geopattern/lib/svg' {
  declare module.exports: any;
}

declare module 'geopattern/lib/xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geopattern/geopattern.js' {
  declare module.exports: $Exports<'geopattern/geopattern'>;
}
declare module 'geopattern/lib/color.js' {
  declare module.exports: $Exports<'geopattern/lib/color'>;
}
declare module 'geopattern/lib/pattern.js' {
  declare module.exports: $Exports<'geopattern/lib/pattern'>;
}
declare module 'geopattern/lib/sha1.js' {
  declare module.exports: $Exports<'geopattern/lib/sha1'>;
}
declare module 'geopattern/lib/svg.js' {
  declare module.exports: $Exports<'geopattern/lib/svg'>;
}
declare module 'geopattern/lib/xml.js' {
  declare module.exports: $Exports<'geopattern/lib/xml'>;
}
