// flow-typed signature: b60801239161844451a5099e665e7bda
// flow-typed version: <<STUB>>/@hackclub/design-system_v^0.0.1-10/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hackclub/design-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hackclub/design-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hackclub/design-system/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/coverage/prettify' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/coverage/sorter' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Avatar' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/BackgroundImage' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Badge' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Box' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Button' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Card' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Container' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Divider' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Field' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Flex' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Heading' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Hide' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Icon' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/IconButton' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Image' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/index' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Input' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Label' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/LargeButton' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Link' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Loading' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/MDIcon' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Module' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/OutlineButton' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Section' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Text' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/theme' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/ThemeProvider' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/dist/Truncate' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/icons' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/scripts/build-icons' {
  declare module.exports: any;
}

declare module '@hackclub/design-system/test-setup' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hackclub/design-system/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'@hackclub/design-system/coverage/lcov-report/prettify'>;
}
declare module '@hackclub/design-system/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'@hackclub/design-system/coverage/lcov-report/sorter'>;
}
declare module '@hackclub/design-system/coverage/prettify.js' {
  declare module.exports: $Exports<'@hackclub/design-system/coverage/prettify'>;
}
declare module '@hackclub/design-system/coverage/sorter.js' {
  declare module.exports: $Exports<'@hackclub/design-system/coverage/sorter'>;
}
declare module '@hackclub/design-system/dist/Avatar.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Avatar'>;
}
declare module '@hackclub/design-system/dist/BackgroundImage.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/BackgroundImage'>;
}
declare module '@hackclub/design-system/dist/Badge.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Badge'>;
}
declare module '@hackclub/design-system/dist/Box.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Box'>;
}
declare module '@hackclub/design-system/dist/Button.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Button'>;
}
declare module '@hackclub/design-system/dist/Card.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Card'>;
}
declare module '@hackclub/design-system/dist/Container.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Container'>;
}
declare module '@hackclub/design-system/dist/Divider.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Divider'>;
}
declare module '@hackclub/design-system/dist/Field.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Field'>;
}
declare module '@hackclub/design-system/dist/Flex.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Flex'>;
}
declare module '@hackclub/design-system/dist/Heading.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Heading'>;
}
declare module '@hackclub/design-system/dist/Hide.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Hide'>;
}
declare module '@hackclub/design-system/dist/Icon.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Icon'>;
}
declare module '@hackclub/design-system/dist/IconButton.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/IconButton'>;
}
declare module '@hackclub/design-system/dist/Image.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Image'>;
}
declare module '@hackclub/design-system/dist/index.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/index'>;
}
declare module '@hackclub/design-system/dist/Input.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Input'>;
}
declare module '@hackclub/design-system/dist/Label.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Label'>;
}
declare module '@hackclub/design-system/dist/LargeButton.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/LargeButton'>;
}
declare module '@hackclub/design-system/dist/Link.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Link'>;
}
declare module '@hackclub/design-system/dist/Loading.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Loading'>;
}
declare module '@hackclub/design-system/dist/MDIcon.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/MDIcon'>;
}
declare module '@hackclub/design-system/dist/Module.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Module'>;
}
declare module '@hackclub/design-system/dist/OutlineButton.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/OutlineButton'>;
}
declare module '@hackclub/design-system/dist/Section.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Section'>;
}
declare module '@hackclub/design-system/dist/Text.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Text'>;
}
declare module '@hackclub/design-system/dist/theme.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/theme'>;
}
declare module '@hackclub/design-system/dist/ThemeProvider.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/ThemeProvider'>;
}
declare module '@hackclub/design-system/dist/Truncate.js' {
  declare module.exports: $Exports<'@hackclub/design-system/dist/Truncate'>;
}
declare module '@hackclub/design-system/icons.js' {
  declare module.exports: $Exports<'@hackclub/design-system/icons'>;
}
declare module '@hackclub/design-system/scripts/build-icons.js' {
  declare module.exports: $Exports<'@hackclub/design-system/scripts/build-icons'>;
}
declare module '@hackclub/design-system/test-setup.js' {
  declare module.exports: $Exports<'@hackclub/design-system/test-setup'>;
}
